config/routes.rb
Rails.application.routes.draw do
 



  get '/login', to: 'users#login_page'
  post '/login', to: 'users#login'
  post '/logout', to: 'users#logout'

  get '/comment/new', to: 'comments#new'

  



  root to: "welcome#show"
  resources :users 
  resources :posts
  resources :comments

  # resources :posts do
  	
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :posts, dependent: :destroy 
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def current_user
  	current_user = User.find_by_id(session[:user_id])
  end


  helper_method :current_user, :current_comment, :logged_in?
  #help_method is for views to acess to the functions.

  def logged_in?
  #boolean return	
  	current_user != nil
  end

  #filter
  def authenticate
  	if !logged_in?
      flash[:message] = 'please login'
      redirect_to '/login'
    end 
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_id(session[:user_id])
    post = Post.find_by_id(params[:id])
    comment = Comment.new(comment_params)
        # @user.posts.create(post_params)
    if comment.save
       flash[:message] = 'Your post was created successfully'
       redirect_to "/posts/#{comment.post_id}"
    else
        flash[:message] = 'try again'
        render '/posts/new'
    end
  end
  
  def show 
  end

  def update
  	comment = Comment.find(params[:id])
    comment.update(comment_params)
    redirect_to "/posts/#{comment.post_id}"  
  end 

  def destroy
  	comment = Comment.find(params[:id])
    comment.destroy
    redirect_to "/posts/#{comment.post_id}" 
  end	



private
  def comment_params
  	params.require(:comment).permit(:message, :user_id, :post_id , :user_id)
  end  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all 
  end

  def new
  end

  def create
  	post = Post.new(post_params)
  	post.user_id = current_user.id
  	if post.save
  		p post.title
  		flash[:message] = 'post created ok'
  		redirect_to "/posts/#{post.id}"
  	else
  		flash[:message] = 'try again'
  		redirect_to posts_new_path
  	end
  end 	

  def show
  	@post = Post.find_by_id(params[:id])
    @comment = Comment.new
    @comments = Comment.where(post_id: params[:id])
  end

  def edit
  end

  def update
  	@post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:message] = 'post edit ok'
      redirect_to "/users/#{current_user.id}"
    else
      flash[:message] = 'try again'
      redirect_to edit_post_path
    end
  end
	
  def destroy
  	post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end	

private
  def post_params
  	params.require(:post).permit(:title, :content, :tag, :user_id)
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only: [:edit, :destroy]
  
  def index
  	@users = User.all  
  end

  def new
    @user = User.new
    render :layout => false	
  end

  def create
  	user = User.new(user_params) 	
    if User.find_by_username(user.username) != nil 
      flash[:message] = "This username belongs to someone else. Let's try somthing new?" 
      redirect_to new_user_path 
    elsif user.save
  		flash[:message] = 'Yes, you got an account now!'
      session[:user_id] = user.id
  		redirect_to "/users/#{user.id}"
  	end
  end

  def show
      @user = User.find_by_id(params[:id])
      if @user != nil
         @post = Post.new
         @posts = Post.where(user_id: params[:id])
         
      else 
         redirect_to '/login' 
      
      end                             
  end

  def edit
  	@user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:message] = 'user edit ok'
      redirect_to "/users/#{@user.id}"
    else
      flash[:message] = 'try again'
      redirect_to edit_user_path
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end

  def login
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id 
      flash[:message] = 'you logged in successfully'
      redirect_to "/users/#{user.id}"
    else 
      flash[:message] = 'try again'
      redirect_to '/login'
    end
  end

  def logout
    session[:user_id] = nil
    flash[:message] = 'logging out ok'
    redirect_to '/login'
  end

  def login_page
    render :layout => false 
  end

private
  def user_params
  	params.require(:user).permit(:username, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show 
  	render :layout => false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMicroBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div id='logo_small'>Clonblr</div>
      <% if logged_in? %>       
        <div class='hello'>Howdy! <%= current_user.username %></div>
        <ul>
          <li><%= link_to image_tag('logout.png', size: "25x25"), logout_path, {method: 'post'} %></li>
          <li><a href="/users/<%=current_user.id%>"><img src="../../assets/user.png" height="25" width="25"/></a></li>
        </ul>   
      <%else%>
        <ul> 
          <div class='login_post'><li><a href='/login'>Login</a></li></div>
        </ul>  
      <% end %>
      <div>
      <ul> 
        <li><a href="/posts"><img src="../../assets/list.png" height="25" width="25"/></a></li>
      </ul>
    </div>
    </nav>
    <% if flash[:message] %>
      <div class='navbar_flashMsg'><%= flash[:message] %></div>
    <% end%>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class='postInx_wrapper'>
<div class='postInx_block'>
<div class='postInx_list'>	
<% @posts.each do |p| %>
    <div class='postInx_each'>
    	<a href="/posts/<%=p.id%>">
	    <a href="/posts/<%=p.id%>">
	        <div class='postInx_title'><%= p.title %></div>
	    </a>
	    <% @auther = User.find_by_id(p.user_id)%>
	    <div class='postInx_meta'>by 
	    	<a href="/users/<%=@auther.id%>"><%= @auther.username %></a> at <i><%= p.created_at.strftime("%a, %b %d, %Y")%></i>
	    </div>
	    <div class='postInx_content'><%= p.content %></div>
	</a>
	</div>
<% end %>
</div>
</div>
</div>

app/views/posts/show.html.erb
<div id='postPage_wrapper'>
  <% if @post != nil%>
    <div id='postPage_column'>
      <div id='article_title'><%= @post.title %></div>
      <% @auther = User.find_by_id(@post.user_id)%>
      <div id='article_meda'>by <a href="/users/<%=@auther.id%>"><%=@auther.username%></a> at <i><%= @post.created_at.strftime("%a, %b %d, %Y")%></i></div>
      <div id='article_text'><%= @post.content %></div>
      <div id='article_tag'>tags: <%= @post.tag %></div>
      <% if current_user != nil %>
        <% if @post.user_id == current_user.id%> 
          <div><img id='article_update_icon' src="../../assets/edit.png" width='25px' height="25px"></div>
          <div id='edit_form_wrapper' >           
            <div id='article_edit_form' >
              <div id='article_edit'>
                <h2>Update the post:</h2>
                <br>
                <%= form_for @post, url: {action: "update"} do |f|%>
                  <div><%= f.text_field :title,  placeholder: "title", class: 'post_edit_input' %></div>
                  <div><%= f.text_area :content, placeholder: "content", style: 'width:80%; height:30vh;', class: 'post_new_text' %></div>
                  <div><%= f.text_field :tag, placeholder: "tag", class: 'post_edit_input' %></div>
                  <div><%= f.submit("Save Post", class: 'post_edit_botton') %></div>
                <% end %>
                <%= form_tag(post_path, method: "delete") do %>
                  <%= submit_tag("Delete Post", class: 'post_delete_botton') %>
                <% end %>
                <div id='cancel_edit_botton'>Cancel</div>
              </div>
            </div>
          </div>
        <%end%>
      <% end %>
      
      <div id='comment_count' align='right'><i><%=@comments.length%> comments</i></div>
      <br>
      <hr>
      <br>
    
    
    <% if current_user != nil %>
      <img id='comment_create_gear' src="../../assets/plus.png" width='25px' height="25px">
      <div id='comment_create_icon'>
            create a comment
      </div>
      <br>
      <div id='comment_create_form'>  
        <%= form_for @comment, :url => comments_path, :method => 'post'  do |f|%>
          <div class='new_comment_form'><%= f.text_area :message,  placeholder: "message", class: 'comment_new_text' %></div>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.hidden_field :post_id, :value => @post.id %>
          <div class='new_comment_form'><%= f.submit("Create comment", class: 'comment_new_save' ) %></div>
        <% end %>
      </div>
    <% end %>
    <br>
    <h2>comments:</h2>
    <% if @comments != [] %>
      <% @comments.each do |c| %>
        <div class='comment_text'><em><%= c.message%></em></div>
        <% @user = User.find_by_id(c.user_id)%>
        <div class='comment_meta'>by <a href="/users/<%=@user.id%>"><%=@user.username%></a> at <%=c.created_at.strftime("%a, %b %d, %Y")%> </div>
        <% if current_user != nil %>
          <% if c.user_id == current_user.id %>
            <div><img class='comment_update_icon' src="../../assets/edit.png" width='25px' height="25px"></div>
            <div class='comment_update_form'>
              <%= form_for @comment, :url => "/comments/#{c.id}", :method => 'put'  do |f| %>
                <div class='update_comment_field'>
                  <%= f.text_area :message, class: 'comment_update_text' %>
                  <%= f.hidden_field :user_id, :value => current_user.id %>
                  <%= f.hidden_field :post_id, :value => @post.id %>
                </div>
                <div class= 'update_comment_field'>
                  <%= f.submit("Save Comment", class: 'comment_update_save') %>
                  <% end %> 
                  <%= form_tag("/comments/#{c.id}", method: "delete") do %>
                  <%= submit_tag("Delete Comment", class: 'comment_delete') %>                        
                  <% end %>
                </div>             
            </div>    
          <% end %>
        <%end%>
      <%end%>
    <% else %>
      <div>Be the first one to leave a comment! <a href="/login"><i><u>  Login here</u></i><a></div> 
    <%end%>
    </div>
  <%else%>
    <div id='not_here'>Opps, this post is not here anymore.</div>
  <%end%>
</div>

<script type="text/javascript" src="/assets/post.js"></script>

app/views/users/login_page.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<div id='login'>
	<% if flash[:message] %>
	     <div class='logout_flashMsg'><%= flash[:message] %></div>
	<% end%>

<div id='logo'>Clonblr</div>

<%= form_tag(login_path) do %>
<div><%= text_field_tag :username, nil, placeholder:'username', class: "input"%></div>
<div><%= text_field_tag :password, nil, placeholder:'password', class: "input" %></div>
<%= submit_tag 'Login', :class => 'user_login' %>

<div class='corner'><a href="/users/new">Sign Up</a></div>

<% end %>

</div>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div id='signup'>
	<% if flash[:message] %>
	<div class='flashMsg'><%= flash[:message] %></div>
	<% end%>
<div id='logo'>Clonblr</div>	

<%= form_for @user do |f| %>


<%= f.text_field :username, placeholder:'username', class: 'input'%><br>
<%= f.text_field :email, placeholder:'email', class: 'input'%><br>
<%= f.text_field :password, placeholder:'password', class: 'input'%><br>
<%= f.submit'SignUp', :class => 'user_create'%>
<% end %>

<div class='corner'><a href="/login">Log In</a></div>

</div>

</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div id='profileWapper'> 
    <div class='profile_column' id='profile_info'>
      <div><img src="../../assets/photo.png" width='200px' height="200px"></div>
      <div id='Username'><%= @user.username %></div>
      <div id='Useemail'><%= @user.email %></div>
      <% if logged_in? %>
        <%if current_user.id == @user.id %>
        <div id='update_user'><img src="../../assets/setting.png" width='20px' height="20px"></div>
        <div id='hidden_user_update'>
          <div id='hidden_user_update_bg'>
            <div id='hidden_user_update_form'>
          <%= form_for @user do |f| %>
          <div id='change_text'>Change your info</div>
          <div>Username:</div>
          <div><%= f.text_field :username, class: 'update_input' %></div>
          <div>Email:</div>
          <div><%= f.text_field :email, class: 'update_input'%></div>
          <div>Password:</div>
            <div><%= f.text_field :password, class: 'update_input'%></div>
          <div id='cancel_botton'>Cancel</div>
          <%= f.submit "Save", class: 'update_botton' %>
          <% end %>
          
          <%= form_tag(user_path, method: "delete") do %>
          <%= submit_tag("Delete Account", :class=>"delete_botton")%>
          
          <% end %>
        </div>
        </div>
        </div>  
    </div>

    <div class='profile_column' id='profile_posts'>
      <div class='new_post'><img src="../../assets/plus.png" width='25px' height="25px"> What's on your mind now?</div>
      <div class='content'>
        <%= form_for @post do |f|%>
          <div><%= f.text_field :title,  placeholder: "title", class: 'post_new_input' %></div>
          <div><%= f.text_area :content, placeholder: "content",style: 'width:80%; height:30vh;', class: 'post_new_text' %></div>
          <div><%= f.text_field :tag, placeholder: "tag", class: 'post_new_tag' %></div>
          <div><%= f.submit'Create', class: 'post_create_botton' %></div>
        <% end %>
       <% end %>
      <%end%>
      </div>

<% @posts.each do |p| %>
 <div id='post_wrapper'> 
   
   <div id='post_time'><%= p.created_at.strftime("%a, %b %d, %Y") %></a></div>
   <div id='post_name'><%= p.title %></div>
   <div id='post_text'><%= p.content %></div>
   <div id= 'look'><a href="/posts/<%=p.id%>"><img src="../../assets/look.png" width='25px' height="25px" align="right"></a></div>
 </div>
<% end%>

</div>

<div class='profile_column' id='profile_comments'>
</div>

</div>

<script type="text/javascript" src="/assets/profile.js"></script>

</body>
</html>

app/views/welcome/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
	<div id='background'>
	<%= video_tag "home.mp4", autoplay: :autoplay, loop: :loop, mute: :mute, class: "video" %>
	<div id='logo'>Clonblr</div>
	<div id='tagline'>a tumblr clone site</div>
	<a href='/users/new'><div id="loginButton">Get Started</div></a>
	<a href='/login'><div id="signinButton">Login</div></a>
	</div>
</body>
</html>	